FROM registry.access.redhat.com/ubi9/python-312@sha256:69aa8a11f6aef38aa5130c44ac94bad8a65e9641b7eaa0a44f04fd7decdf8be2
WORKDIR /opt/app-root

RUN pip install sqlalchemy # somehow sqlalchemy[asyncio] is not sufficient
{dependencies}
RUN pip install --no-cache llama-stack==0.2.18
RUN mkdir -p ${{HOME}}/.llama/providers.d ${{HOME}}/.cache
COPY distribution/run.yaml ${{APP_ROOT}}/run.yaml
COPY distribution/providers.d/ ${{HOME}}/.llama/providers.d/

ENTRYPOINT ["python", "-m", "llama_stack.core.server.server", "/opt/app-root/run.yaml"]
