FROM registry.access.redhat.com/ubi9/python-312@sha256:95ec8d3ee9f875da011639213fd254256c29bc58861ac0b11f290a291fa04435
WORKDIR /opt/app-root

COPY --chmod=755 distribution/install-deps.sh distribution/install-common.sh /tmp/
RUN /tmp/install-common.sh

COPY distribution/config.yaml ${APP_ROOT}/config.yaml
COPY --chmod=755 distribution/entrypoint.sh ${APP_ROOT}/entrypoint.sh

ENV TIKTOKEN_CACHE_DIR="${HOME}/.cache/tiktoken"
#TODO: remove this once we have a stable version of llama-stack
ENV LLAMA_STACK_DISABLE_VERSION_CHECK=true

ENTRYPOINT [ "/opt/app-root/entrypoint.sh" ]
