#!/bin/bash
# Common installation steps for llama-stack containers
# Used by both distribution/Containerfile and Dockerfile.konflux

set -euo pipefail

pip install uv
pip install sqlalchemy # sqlalchemy[asyncio] alone is not sufficient
uv pip install opentelemetry-distro
uv pip install structlog # core llama-stack dep not covered by provider deps

# Install dependencies (generated by build.py)
/tmp/install-deps.sh

# Install opentelemetry instrumentation packages
opentelemetry-bootstrap -a requirements | grep -v -e botocore -e system-metrics | uv pip install --requirement -


# Create cache directories
mkdir -p ${HOME}/.llama ${HOME}/.cache

# Pre-cache tiktoken cl100k_base encoding to avoid runtime download
export TIKTOKEN_CACHE_DIR="${HOME}/.cache/tiktoken"
python3 -c "import tiktoken; tiktoken.get_encoding('cl100k_base')"
