#!/bin/bash
# WARNING: This file is auto-generated. Do not modify it manually.
# Generated by: distribution/build.py

set -euo pipefail

uv pip install --upgrade \
'kfp-kubernetes==2.14.6' \
'pyarrow>=21.0.0' \
'botocore==1.35.88' \
'boto3==1.35.88' \
'aiobotocore==2.16.1' \
'ibm-cos-sdk-core==2.14.2' \
'ibm-cos-sdk==2.14.2' \
'setuptools==81.0.0'
uv pip install \
'datasets>=4.0.0' \
'fonttools>=4.60.2' \
'mcp>=1.23.0' \
'nltk>=3.9.4' \
'pymilvus==2.6.9' \
'pymilvus[milvus-lite]==2.6.9' \
'pypdf>=6.7.2' \
aiosqlite \
asyncpg \
autoevals \
boto3 \
chardet \
einops \
faiss-cpu \
fastapi \
fire \
google-genai \
httpx \
matplotlib \
numpy \
opentelemetry-exporter-otlp-proto-http \
opentelemetry-sdk \
pandas \
pillow \
psycopg2-binary \
pymongo \
qdrant-client \
redis \
requests \
safetensors \
scikit-learn \
scipy \
sentencepiece \
sqlalchemy[asyncio] \
tokenizers \
tqdm \
transformers \
uvicorn
uv pip install \
llama_stack_provider_lmeval==0.5.0
uv pip install \
llama_stack_provider_ragas[inline]==0.6.1
uv pip install \
llama_stack_provider_ragas[remote]==0.6.1
uv pip install \
llama_stack_provider_trustyai_fms==0.4.0
uv pip install \
llama_stack_provider_trustyai_garak==0.3.1
uv pip install --extra-index-url https://download.pytorch.org/whl/cpu 'torchao>=0.12.0' torch torchvision
uv pip install --no-deps sentence-transformers

uv pip install --no-cache --no-deps git+https://github.com/opendatahub-io/llama-stack.git@v0.7.1+rhaiv.1
uv pip install --no-cache --no-deps llama-stack-client==0.7.2
